# Generated by Django 2.2.9 on 2020-04-10 21:24

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', jsonfield.fields.JSONField(default=None, max_length=8192, null=True)),
                ('measures', jsonfield.fields.JSONField(default=None, max_length=8192, null=True)),
                ('filters', jsonfield.fields.JSONField(default=None, max_length=8192, null=True)),
                ('model', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='contenttypes.ContentType')),
            ],
        ),
    ]
