# Generated by Django 2.2.9 on 2020-04-12 17:33

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_reporter_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='searches',
            field=jsonfield.fields.JSONField(default=None, max_length=8192, null=True),
        ),
    ]
