# Generated by Django 2.2.9 on 2020-04-18 08:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_reporter_pro', '0002_reportconfiguration_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='report_config',
            field=jsonfield.fields.JSONField(default=None, max_length=8192, null=True),
        ),
    ]
