# Generated by Django 2.2.9 on 2020-04-22 16:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_reporter_pro', '0003_reportconfiguration_report_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='information',
            field=jsonfield.fields.JSONField(default=None, max_length=8192, null=True),
        ),
    ]
