# Generated by Django 2.2.9 on 2020-04-24 18:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_reporter_pro', '0004_reportconfiguration_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfiguration',
            name='dimensions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='information',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='measures',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='report_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='searches',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, max_length=8192, null=True),
        ),
    ]
