# Generated by Django 2.2.9 on 2020-05-09 05:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_reporter_pro', '0005_auto_20200424_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='orders',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, max_length=8192, null=True),
        ),
    ]
