# Generated by Django 2.2.9 on 2020-05-24 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_reporter_pro', '0006_reportconfiguration_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
