# Generated by Django 2.2.9 on 2020-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_reporter_pro', '0007_auto_20200524_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='is_deleted',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
